
name: Run Tests
on:
  push:
    branches-ignore: [ 'doc', 'develop' ]
  pull_request:

  # to manually trigger a workflow on GitHub
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Install sbt
        if: runner.os == 'macOS'
        run: brew install sbt
      - name: Install Xvfb (Ubuntu only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y xvfb
      - name: Run tests (Ubuntu with Xvfb, others normally)
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run --auto-servernum sbt test
          else
            sbt test
          fi
        shell: bash

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Check scalafmt format
        run: sbt scalafmtCheckAll
